services:
  db:
    image: mysql:5.7
    container_name: solftsul_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3308:${DB_PORT}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - solftsul-network
    mem_limit: 2g        
    mem_reservation: 1g 

  phpmyadmin:
    image: phpmyadmin
    container_name: solftsul_sgbd
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    networks:
      - solftsul-network
    depends_on:
      - db

  app:
    build: .
    container_name: solftsul
    image: solftsul
    restart: always
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www/html/challenge-softsul
    networks:
      - solftsul-network
    depends_on:
      - db

networks:
  solftsul-network:


volumes:
  db_data:
